services:
    php:
        image: php-starter-php
        build:
            context: .
            dockerfile: .docker/Dockerfile
            target: frankenphp_dev
        environment:
            SERVER_NAME: ":80"
        volumes:
            - ./:/app
            - ./.docker/franken/Caddyfile:/etc/caddy/Caddyfile
            - ~/.composer:/root/.composer:delegated
            - starter_caddy_data:/data
            - starter_caddy_config:/config
        tty: true
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.starter.loadbalancer.server.port=80

                - traefik.http.routers.starter.rule=Host(`starter.local.barlito.fr`)
                - traefik.http.routers.starter.entrypoints=http
#                - traefik.http.routers.starter.middlewares=tls-redirectscheme

                - traefik.http.routers.starter-secure.rule=Host(`starter.local.barlito.fr`)
                - traefik.http.routers.starter-secure.entrypoints=https
                - traefik.http.routers.starter-secure.tls=true
        networks:
            - traefik_traefik_proxy

volumes:
    starter_caddy_data:
    starter_caddy_config:

networks:
    traefik_traefik_proxy:
        external: true
